Errors with vagrant & chef-solo
ERROR: Cookbook loaded at path(s) [/tmp/vagrant-chef-3/chef-solo-1/cookbooks/mule] has invalid metadata: The `name' at
tribute is required in cookbook metadata